### ISSUE TITLE
mise.el prevents setenv in eshell-mode-hook from setting variables

### ISSUE THREAD

**Issue by shassard** [liuyinz/mise.el#2]
I have an `eshell-mode-hook` that worked well before using mise.el:
```
(add-hook 'eshell-mode-hook (lambda () (setenv "PAGER" "cat")))
```
After setting an eshell to `mise-mode`, the `setenv` function in the hook stops functioning.

Disabling `mise-mode`'s eshell integration fixes the issue (via setting `mise-update-on-eshell-directory-change` to `nil`.

It'd be nice to have some way of re-enabling that functionality. It was confusing that `mise-mode` broke that until I spent some time working through a bunch of my config changes to find the root cause.

**Comment by liuyinz** [comment]
does https://github.com/liuyinz/mise.el/commit/92c24f06d8d47028ea30ba1c27808ed638372c12 fix your problem ?

**Comment by shassard** [comment]
That fixes the issue for me. Thanks!
