### ISSUE TITLE
mise.el hooks don't run before `projectil-compile-project`, `projectile-run-async-shell-command-in-root`

### ISSUE THREAD

**Issue by afontaine** [liuyinz/mise.el#3]
I am assuming I need to configure these two commands specifically to account for `mise`, but running `mise-mode` as part of `compilation-mode-hook` doesn't do the trick. 

Any guidance here would be very helpful :bow:

**Comment by liuyinz** [comment]
Could you clarify what you’re asking for? I’m not sure I understand.

**Comment by afontaine** [comment]
perhaps a picture may help

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/1ef964ac-e3aa-41bf-8215-9271f039f48b">


basically though, the mise path changes aren't picked up in `compile` buffers while they are in text and vterm buffers.

**Comment by liuyinz** [comment]
I test my compilation is fine,  maybe add your commands into `mise-auto-propagate-commands` ?

**Comment by afontaine** [comment]
Ah, it works, but not in my daemon. must be a misconfiguration somewhere. I'll keep digging into it.

Cheers!

/close
